### ISSUE TITLE
Any plans for a windows build?

### ISSUE THREAD

**Issue by justa9** [thomasp85/hierarchicalSets#1]
Hello.

Are there any plans for a windows build? 

The current source doesn't seem to compile.

**Comment by thomasp85** [comment]
Yes - I'm looking into it

**Comment by thomasp85** [comment]
Submitted a fix to CRAN, but you should also be able to install directly from GitHub now

**Comment by thomasp85** [comment]
Is on CRAN now - pre-builds for windows can happen anytime
